#!/bin/sh
rsblocks &
xrandr --dpi 96
xrandr --setprovideroutputsource modesetting NVIDIA-0 
xrandr --auto 
picom -f &
nitrogen --restore &
setxkbmap tr &
xset r rate 300 50 &
exec dwm
xrandr --output eDP-1-1 --set "PRIME Synchronization" 1 &
