export ZSH="$HOME/.oh-my-zsh"

alias e="nvim"
alias xin="sudo xbps-install"
alias fixsc='xrandr --output eDP-1-1 --set "PRIME Synchronization" 1'
alias xre="sudo xbps-remove -R"
alias xse="xbps-query -s"

source $ZSH/oh-my-zsh.sh
source ~/.antigen.zsh

antigen use oh-my-zsh

antigen bundle git
antigen bundle rust
antigen bundle colored-man-pages
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle zsh-users/zsh-completions
antigen bundle zsh-users/zsh-autosuggestions
antigen apply

# ~/.zshrc

eval "$(starship init zsh)"

